CREATE TABLE USERS
(
  ID       INTEGER PRIMARY KEY AUTO_INCREMENT,
  EMAIL    VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  ROLE     VARCHAR(20) NOT NULL,
  UNIQUE (EMAIL)
);

CREATE TABLE ORGANIZATION
(
  ID       INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME     VARCHAR(30) NOT NULL,
  STATUS   VARCHAR(20) NOT NULL
);

CREATE TABLE USERS_TO_ORGANIZATION
(
  ID              INTEGER PRIMARY KEY AUTO_INCREMENT,
  USER_ID         INTEGER,
  ORGANIZATION_ID INTEGER,
  CONSTRAINT `fk_USERS_TO_ORGANIZATION_USER_ID` FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT `fk_USERS_TO_ORGANIZATION_ORGANIZATION_ID` FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
  UNIQUE(USER_ID, ORGANIZATION_ID)
);

CREATE TABLE PROJECT
(
  ID              INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME            VARCHAR(30) NOT NULL,
  ORGANIZATION_ID INTEGER,
  DESCRIPTION     TEXT        NOT NULL,
  CONSTRAINT `fk_PROJECT_ORGANIZATION_ID` FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID)
);

CREATE TABLE VERSION
(
  ID          INTEGER PRIMARY KEY AUTO_INCREMENT,
  RANK        VARCHAR(50) NOT NULL,
  PROJECT_ID  INTEGER,
  DESCRIPTION TEXT,
  CONSTRAINT `fk_VERSION_PROJECT_ID` FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID)
);